### ISSUE TITLE
does not install on Linux Mint 17 x64

### ISSUE THREAD

**Issue by ShvonderSiN** [isamert/addalias#2]
on the virtual machine set, all OK.
On the main machine installation fails with the following

~/addalias-master/src $ python addalias.py --install
Traceback (most recent call last):
  File "addalias.py", line 278, in <module>
    main()
TypeError: main() takes exactly 1 argument (0 given)

**Comment by isamert** [comment]
Thank you for reporting.  It must happened because of some python uptade or something, I dont know :). I fixed the error, now you can install and use it.
